COINCA.WebApp.ECOsystem/Areas/Coinca/Controllers/PartnerNewsController.cs
using ECOsystem.Audit;
using  ECOsystem.Areas.Coinca.Business;
using ECOsystem.Business.Utilities;
using ECOsystem.Models.Account;
using  ECOsystem.Areas.Coinca.Models.Identity;
using ECOsystem.Models.Miscellaneous;
using  ECOsystem.Areas.Coinca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;




namespace  ECOsystem.Areas.Coinca.Controllers
{
    /// <summary>
    /// Partner News Controller
    /// </summary>
    public class PartnerNewsController : Controller
    {
        /// <summary>
        /// Partners Main View
        /// </summary>
        /// <returns>A object that renders a view. This string representation would be written to the Response stream during execution</returns>
        [EcoAuthorize]
        public ActionResult Index()
        {
            using (var business = new PartnerNewsBusiness())
            {
                PartnerNews newsModel  = new PartnerNews();
                int? partnerId = ECOsystem.Utilities.Session.GetPartnerId();
                IEnumerable<PartnerNews> partnersNews;
                if (User.IsInRole("PARTNER_ADMIN"))
                {
                    newsModel.PartnerId = (int)partnerId;
                    partnersNews = business.RetrieveNewsByPartners(partnerId, null);
                }
                else {
                    partnerId = null;
                    partnersNews = business.RetrieveAllNewsByPartners(null);
                }
               
                var model = new PartnersNewsBase
                {
                    Data = newsModel,
                    List = partnersNews,
                    Menus = new List<AccountMenus>()
                };
               
                return View(model);
            }
        }

        /// <summary>
        /// Performs the maintenance Insert or Update of the entity Partners
        /// </summary>
        /// <param name="model">Model or class passed as parameter  which contains all properties to perform insert or update operations</param>
        /// <returns>A object that renders a partial view. This string representation would be written to the Response stream during execution</returns>
        [HttpPost]
        [EcoAuthorize]
        public PartialViewResult AddOrEditPartnerNews(PartnerNews model)
        {
            try
            {
                using (var business = new PartnerNewsBusiness())
                {
                  
                    business.AddOrEditNewsByPartners(model);

                    IEnumerable<PartnerNews> partnersNews;
                    if (User.IsInRole("PARTNER_ADMIN"))
                    {
                        partnersNews = business.RetrieveNewsByPartners(ECOsystem.Utilities.Session.GetPartnerId(), null);
                    }
                    else
                    {
                        partnersNews = business.RetrieveAllNewsByPartners(null);
                    }
               
                    return PartialView("_partials/_Grid", partnersNews);
                }
            }
            catch (Exception e)
            {
                ECOsystem.Utilities.Session.SentrySupport(e);

                //Add log event
                new EventLogBusiness().AddLogEvent(LogState.ERROR, e.Message);

                return PartialView("~/Views/Shared/_PartialError.cshtml", new CustomError()
                {
                    TechnicalError = e.Message + e.StackTrace,
                    ReturnUlr = Url.Action("Index", "Partners")
                });
            }
        }

        /// <summary>
        /// Search Partners
        /// </summary>
        /// <param name="key">Key is the search criteria to find a record using a value and it trying to lookup the value through multiple columns</param>
        /// <returns>A object that renders a partial view. This string representation would be written to the Response stream during execution</returns>
        [HttpPost]
        public PartialViewResult SearchPartnerNews(string key)
        {
            try
            {
                using (var business = new PartnerNewsBusiness())
                {
                    IEnumerable<PartnerNews> partnersNews;
                    if (User.IsInRole("PARTNER_ADMIN"))
                    {
                        partnersNews = business.RetrieveNewsByPartners(ECOsystem.Utilities.Session.GetPartnerId(), null, key);
                    }
                    else
                    {
                        partnersNews = business.RetrieveAllNewsByPartners(null);
                    }
                    return PartialView("_partials/_Grid", partnersNews);
                }
            }
            catch (Exception e)
            {
                ECOsystem.Utilities.Session.SentrySupport(e);

                //Add log event
                new EventLogBusiness().AddLogEvent(LogState.ERROR, e.Message);

                return PartialView("~/Views/Shared/_PartialError.cshtml", new CustomError()
                {
                    TechnicalError = e.Message + e.StackTrace,
                    ReturnUlr = Url.Action("Index", "Partners")
                });
            }
        }

        /// <summary>
        /// Load Partners
        /// </summary>
        /// <param name="id">The PRIMARY KEY uniquely that identifies each record of this model</param>
        /// <returns>A object that renders a partial view. This string representation would be written to the Response stream during execution</returns>
        [HttpPost]
        [EcoAuthorize]
        public PartialViewResult LoadPartnerNews(int id)
        {
            try
            {
                using (var business = new PartnerNewsBusiness())
                {
                    if (User.IsInRole("PARTNER_ADMIN"))
                    {
                        return PartialView("_partials/_Detail", business.RetrieveNewsByPartners(ECOsystem.Utilities.Session.GetPartnerId(), id).FirstOrDefault());
                    }
                    else
                    {
                        return PartialView("_partials/_Detail", business.RetrieveNewsByPartners(null, id).FirstOrDefault());
                    }
                  
                }
            }
            catch (Exception e)
            {
                ECOsystem.Utilities.Session.SentrySupport(e);

                //Add log event
                new EventLogBusiness().AddLogEvent(LogState.ERROR, e.Message);

                return PartialView("~/Views/Shared/_PartialError.cshtml", new CustomError()
                {
                    TechnicalError = e.Message + e.StackTrace,
                    ReturnUlr = Url.Action("Index", "Partners")
                });
            }
        }

        /// <summary>
        /// Performs the the operation of delete on the model Partners
        /// </summary>
        /// <param name="id">The PRIMARY KEY uniquely that identifies each record of this model</param>
        /// <returns>A object that renders a partial view. This string representation would be written to the Response stream during execution</returns>
        [HttpPost]
        [EcoAuthorize]
        public PartialViewResult DeletePartnerNews(int id)
        {
            try
            {
                using (var business = new PartnerNewsBusiness())
                {
                    business.DeleteNewsByPartners(id);
                    IEnumerable<PartnerNews> partnersNews;
                    if (User.IsInRole("PARTNER_ADMIN"))
                    {
                        partnersNews = business.RetrieveNewsByPartners(ECOsystem.Utilities.Session.GetPartnerId(), null);
                    }
                    else
                    {
                        partnersNews = business.RetrieveAllNewsByPartners(null);
                    }
                    return PartialView("_partials/_Grid", partnersNews);
                }
            }


            catch (Exception e)
            {
                ECOsystem.Utilities.Session.SentrySupport(e);

                //Add log event
                new EventLogBusiness().AddLogEvent(LogState.ERROR, e.Message);

                if (e.Message.Contains("REFERENCE constraint"))
                {
                    return PartialView("~/Views/Shared/_PartialErrorAttention.cshtml", new CustomError()
                    {
                        TitleError = "Eliminación de Registro",
                        TechnicalError = "El registro se encuentra asociado a otros datos, no es posible eliminarlo.",
                        ReturnUlr = Url.Action("Index", "Partners")
                    });
                }
                else
                {
                    return PartialView("~/Views/Shared/_PartialError.cshtml", new CustomError()
                    {
                        TechnicalError = e.Message + e.StackTrace,
                        ReturnUlr = Url.Action("Index", "Partners")
                    });
                }
            }
        }

        #region Log

        /// <summary>
        /// Add log event for this Controller
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="customerId"></param>
        /// <param name="partnerId"></param>
        /// <param name="message"></param>
        /// <param name="isWarning"></param>
        /// <param name="isInfo"></param>
        /// <param name="isError"></param>
        public void AddLogEvent(Exception exception, int? userId = null, int? customerId = null, int? partnerId = null, bool isWarning = false, bool isInfo = false, bool isError = false)
        {

            EventLogBusiness.AddEventLog(new EventLog()
            {
                UserId = userId,
                CustomerId = customerId,
                PartnerId = partnerId,
                Controller = this.ControllerContext.RouteData.Values["controller"].ToString(),

COINCA.WebApp.ECOsystem/Areas/Coinca/Views/PartnerNews/Index.cshtml
@model  ECOsystem.Areas.Coinca.Models.PartnersNewsBase
@{
    ViewBag.Title = "Mantenimiento Noticias";
    ViewBag.Administration = "active";
    var header = ECOsystem.Controllers.Account.ASPMenusController.GetHeader();
    ViewBag.HasGrid = true;

    Layout = "~/Views/Shared/_Layout.cshtml";

    string version = ViewContext.Controller.GetType().Assembly.GetName().Version.ToString();
}

@section styles {
    <style>
        img.pic {
            border: solid 1px #BCBCBC;
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            margin-bottom: 2px;
        }

        .imgtainer {
            position: relative;
        }

        .progress_bar {
            position: absolute;
            padding: 3px;
            border: 1px solid #000;
            font-size: 14px;
            clear: both;
            opacity: 0;
            -moz-transition: opacity 1s linear;
            -o-transition: opacity 1s linear;
            -webkit-transition: opacity 1s linear;
            width: 246px;
            top: 10px;
            left: 20px;
        }

            .progress_bar.loading {
                opacity: 1.0;
            }

            .progress_bar .percent {
                background-color: #3090d1;
                height: auto;
                width: 0;
                padding-left: 5px;
            }

        .imgloading {
            opacity: 0.3;
            background: #808080;
        }
    </style>

}


@using (Ajax.BeginForm("AddOrEditPartnerNews", "PartnerNews", null, new AjaxOptions
{
    HttpMethod = "post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "gridContainer",
    OnSuccess = "ECOsystem.Utilities.AddOrEditModalClose()"
}, new { id = "addOrEditForm" }))
{
    <div id="detailContainer">
        @Html.Partial("_partials/_Detail", Model.Data)
    </div>
}

<div id="wrapper">
    @using (Ajax.BeginForm("LoadMenus", "ASPMenus", new { area = ""}, new AjaxOptions
    {
        HttpMethod = "post",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "side-menu2",
        OnSuccess = "updateSidebar()"
    }, new { id = "LoadMenuForm" }))
    {
        <input class="hidden" name="Header" value="9" />
        @Html.Partial("~/Views/Shared/_Menu.cshtml", Model.Menus)
    }

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">@ViewBag.Title</h3>
            </div>
        </div>

        <!-- Search Area Start-->
        @using (Ajax.BeginForm("SearchPartnerNews", "PartnerNews", null, new AjaxOptions
            {
                HttpMethod = "post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "gridContainer",
                OnSuccess = "ECOsystem.Utilities.SuccessSearch()"
            }, new { id = "searchForm" }))
        {
            <div class="row">
                <div class="col-sm-11">
                    <div class="input-group">

                        <input id="txtSearch" name="key" type="text" class="form-control" placeholder="Buscar...">

                        <span class="input-group-btn">
                            <button id="btnSearch" type="submit" class="btn btn-primary" title="Buscar"><i class="glyphicon glyphicon-search"></i></button>
                        </span>

                    </div>
                </div>
                <div class="col-sm-1 text-right">
                    <button id="btnAdd" type="button" class="btn btn-success" data-toggle="modal" data-target="#addOrEditModal" title="Agregar"><i class="mdi mdi-plus mdi-18px"></i></button>
                </div>
            </div>
        }
        <!-- Search Area End-->
        <!-- Load Form Start-->
        @using (Ajax.BeginForm("LoadPartnerNews", "PartnerNews", null, new AjaxOptions
        {
            HttpMethod = "post",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "detailContainer",
            OnSuccess = " ECOsystem.Areas.Coinca.PartnerNews.OnSuccessLoad()"
        }, new { id = "loadForm" }))
        {
            @Html.Hidden("id")
        }
        <!-- Load Form End-->
        <!-- Dele Modal Start-->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="addOrEditModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    @using (Ajax.BeginForm("DeletePartnerNews", "PartnerNews", null, new AjaxOptions
                    {
                        HttpMethod = "post",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "gridContainer",
                        OnSuccess = "ECOsystem.Utilities.DeleteModalClose()"
                    }, new { id = "deleteForm" }))
                    {
                        @Html.Hidden("id")
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title">Confirmar Eliminación</h4>
                        </div>
                        <div class="modal-body">
                            <p>¿Está seguro que desea eliminar el registro?</p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i>&nbsp;Cancelar</button>
                            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i>&nbsp;Aceptar</button>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- Delete Modal End -->

        <div class="row">
            <div class="col-lg-12" id="gridContainer">
                @Html.Partial("_partials/_Grid", Model.List)
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script src="~/Scripts/Settings/partnernews.js?v=@version-hf0"></script>
    <script>
        $(function () {
            $("#LoadMenuForm").submit();
             ECOsystem.Areas.Coinca.PartnerNews.Init();
        });

    </script>
}